### ISSUE TITLE
Hairstyle Listbox TGUI Crash

### ISSUE THREAD

**Issue by KillianKirilenko** [VOREStation/VOREStation#10884]
#### Brief description of the bug

Trying to use the search field for a list which *only* has uppercase entries (e.g. hairstyles) causes a TGUI crash.

#### What you expected to happen

For the list to show non-lowercase items as well, e.g. "po" would match the various types of "Ponytail", and for searching with uppercase to work normally.

#### What actually happened

TGUI crash!

```
TypeError: Unable to get property 'toLowerCase' of undefined or null reference
   at Anonymous function (http://127.0.0.1:54723/tmp18704/tgui.bundle.js:1:326969)
   at Anonymous function (http://127.0.0.1:54723/tmp18704/tgui-common.bundle.js:1:40606)
   at filter (http://127.0.0.1:54723/tmp18704/tgui-common.bundle.js:1:85156)
   at onInput (http://127.0.0.1:54723/tmp18704/tgui.bundle.js:1:326938)
   at t.handleInput (http://127.0.0.1:54723/tmp18704/tgui-common.bundle.js:1:274794)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"(my ckey)","interface":"ListInput","window":{"key":"[0x210b6050]-main","size":null,"fancy":1,"locked":0}}
```

#### Steps to reproduce
- Open the searchbar for the hairstyle listbox
- Start searching
- Get a crash!

#### Notes
Running the latest BYOND beta.

**Comment by SplinterGP** [comment]
seems like there's nulls in the list.

**Comment by JoanRisu** [comment]
Related, it seems when I hit alt on my keyboard while this window is focused, I get the crash. 

```
TypeError: Unable to get property 'substring' of undefined or null reference
   at Anonymous function (http://127.0.0.1:62875/tmp28852/tgui.bundle.js:1:326254)
   at Anonymous function (http://127.0.0.1:62875/tmp28852/tgui-common.bundle.js:1:40606)
   at filter (http://127.0.0.1:62875/tmp28852/tgui-common.bundle.js:1:85156)
   at onKeyDown (http://127.0.0.1:62875/tmp28852/tgui.bundle.js:1:326226)
   at $ (http://127.0.0.1:62875/tmp28852/tgui-common.bundle.js:1:167712)
   at Anonymous function (http://127.0.0.1:62875/tmp28852/tgui-common.bundle.js:1:167378)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Zoom 3.6.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"joanrisu","interface":"ListInput","window":{"key":"[0x210bd479]-main","size":null,"fancy":1,"locked":0}}
```
