### ISSUE TITLE
[UI] Deconstructing anything bluescreens the TGUI menu

### ISSUE THREAD

**Issue by scarletflared** [VOREStation/VOREStation#16089]
#### Brief description of the bug
Placing anything into the Destructive Analyser and clicking Deconstruct bluescreens the TGUI menu, requiring it to be closed and reopened after each deconstruction. Resyncing with nearby devices also causes a bluescreen.

#### What you expected to happen
Deconstruction as normal.

#### What actually happened
After deconstructing, the RD console screen displayed this error message:

A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/VOREStation/VOREStation. Thank you for your cooperation. 
 TypeError: Unable to get property 'linked_lathe' of undefined or null reference
   at v (http://127.0.0.1:62693/tmp4912/asset.722165218afc41557fedb115b7755cd5.js:295:510510)
   at Kl (http://127.0.0.1:62693/tmp4912/asset.722165218afc41557fedb115b7755cd5.js:9:65459)
   at zl (http://127.0.0.1:62693/tmp4912/asset.722165218afc41557fedb115b7755cd5.js:9:77234)
   at Su (http://127.0.0.1:62693/tmp4912/asset.722165218afc41557fedb115b7755cd5.js:9:119542)
   at bu (http://127.0.0.1:62693/tmp4912/asset.722165218afc41557fedb115b7755cd5.js:9:114478)
   at td (http://127.0.0.1:62693/tmp4912/asset.722165218afc41557fedb115b7755cd5.js:9:114412)
   at Xs (http://127.0.0.1:62693/tmp4912/asset.722165218afc41557fedb115b7755cd5.js:9:114265)
   at ic (http://127.0.0.1:62693/tmp4912/asset.722165218afc41557fedb115b7755cd5.js:9:110486)
   at yu (http://127.0.0.1:62693/tmp4912/asset.722165218afc41557fedb115b7755cd5.js:9:109472)
   at _ (http://127.0.0.1:62693/tmp4912/asset.722165218afc41557fedb115b7755cd5.js:33:1556)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E)
State: {"ckey":"awesierra","interface":"ResearchConsole","window":{"key":"[0x2000a0a]-main","size":null,"fancy":1,"locked":0}}

Nanotrasen (c) 2284-300 

#### Steps to reproduce
Step 1: Play Stellar Delight
Step 2: Deconstruct anything
Step 3: Marvel at excellently crafted TGUI bluescreen menu.

**Comment by Kashargul** [comment]
https://github.com/CHOMPStation2/CHOMPStation2/issues/8619
