### ISSUE TITLE
[GENERAL] Virology Disease Splicer is unable to function

### ISSUE THREAD

**Issue by Zallicity** [VOREStation/VOREStation#16151]
#### Brief description of the bug
An error occurs when a Virus Sample is incubated and analyzed and placed into the Splicer. The Splicer can be used without a sample loaded. 

#### What you expected to happen
When a Sample is loaded; symptom listings along with their various stats and vectors of infection.

#### What actually happened
A blue screen is shown with the following error messages;
TypeError: Object doesn't support property or method 'map'
   at g (http://127.0.0.1:63482/asset.2faf35dc5324b9abffd7a75a03d502b4.js:295:200204)
   at Pi (http://127.0.0.1:63482/asset.2faf35dc5324b9abffd7a75a03d502b4.js:9:62920)
   at bu (http://127.0.0.1:63482/asset.2faf35dc5324b9abffd7a75a03d502b4.js:9:118745)
   at Pu (http://127.0.0.1:63482/asset.2faf35dc5324b9abffd7a75a03d502b4.js:9:114394)
   at nd (http://127.0.0.1:63482/asset.2faf35dc5324b9abffd7a75a03d502b4.js:9:114328)
   at Ns (http://127.0.0.1:63482/asset.2faf35dc5324b9abffd7a75a03d502b4.js:9:114181)
   at nc (http://127.0.0.1:63482/asset.2faf35dc5324b9abffd7a75a03d502b4.js:9:110403)
   at yu (http://127.0.0.1:63482/asset.2faf35dc5324b9abffd7a75a03d502b4.js:9:109389)
   at P (http://127.0.0.1:63482/asset.2faf35dc5324b9abffd7a75a03d502b4.js:33:1585)
   at z (http://127.0.0.1:63482/asset.2faf35dc5324b9abffd7a75a03d502b4.js:33:1951)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"jadepilot","interface":"DiseaseSplicer","window":{"key":"[0x2000fdd]-main","size":null,"fancy":1,"locked":0}}

#### Steps to reproduce
- (Step 1) Obtain Virus Sample
- (Step 2) Place Sample into Virus Incubator
- (Step 3) Incubate to sufficient Growth
- (Step 4) Place Sample into Disease Analyzer
- (Step 5) Place Sample into Disease Splicer

**Comment by Kashargul** [comment]
Seems like symptoms are no proper list? Something to look into when I have some time.
